[package]
name = "wert"
version = "0.1.0"
authors = ["Ross Guarino <ross@rlg.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
indicatif = "0.16.2"